CREATE TABLE livro (
 id INT PRIMARY KEY AUTO_INCREMENT,
 titulo VARCHAR(100) NOT NULL,
 genero VARCHAR (30) NOT NULL,
 editora VARCHAR (50) NOT NULL,
 isbn VARCHAR (15) NOT NULL UNIQUE,
 autor VARCHAR (100) NOT NULL
 );
 
 