CREATE TABLE IF NOT EXISTS funcionario(
Id INT PRIMARY KEY AUTO_INCREMENT,
NomeCompleto VARCHAR(100) NOT  NULL,
Cpf VARCHAR(14) NOT NULL UNIQUE,
Rg VARCHAR(20) NOT NULL,
DataNascimento DATE,
Genero VARCHAR(20) NOT NULL,
EstadoCivil VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Endereco(

Id INT PRIMARY KEY AUTO_INCREMENT,

FuncionarioId INT NOT NULL,

Cep VARCHAR(50) NOT NULL,

Logradouro VARCHAR(50) NOT NULL,

Numero VARCHAR(10) NOT NULL,

Complemento VARCHAR(30) NOT NULL,

Bairro VARCHAR(100) NOT NULL,

Cidade VARCHAR(100) NOT NULL, 

Estado VARCHAR (2) NOT NULL,

FOREIGN KEY (FuncionarioId) REFERENCES Funcionario(Id)

);
 
 CREATE TABLE IF NOT EXISTS funcao(
Id  INT PRIMARY KEY AUTO_INCREMENT,
FuncionarioId INT NOT NULL,
Cargo VARCHAR(50) NOT NULL,
Departamento VARCHAR(60) NOT NULL,
DataAdmissao DATE NOT NULL,
Salario DECIMAL(10,2) NOT NULL,
FOREIGN KEY (FuncionarioId) REFERENCES Funcionario(Id)
);

CREATE TABLE IF NOT EXISTS dadospessoais (

id INT PRIMARY KEY AUTO_INCREMENT,

nomecompleto VARCHAR(100) NOT NULL,

cpf VARCHAR(25) NOT NULL,

rg VARCHAR(15) NOT NULL,

datadenascimento DATE ,

genero VARCHAR(40) NOT NULL,

estadocivil VARCHAR(50) NOT NULL
 
);

CREATE TABLE IF NOT EXISTS usuario (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    NomeUsuario VARCHAR(50) NOT NULL,
    Senha VARCHAR(100) NOT NULL
);

INSERT INTO usuario (NomeUsuario, Senha) VALUES ('admin', 'senha1234')
 